 /******************************************************************************
 *
 * Module : Port
 *
 * File Name: Port_PBcfg.c
 *
 * Description: Post Build Configuration Source file for TM4C123GH6PM Microcontroller - Port Driver
 *
 * Author: Abdulrahman yasser
 ******************************************************************************/


// #include "memMap.h"
// #include "Port_cbk.h"


#include "Port.h"

/*
 * Module Version 1.0.0
 */
#define PORT_PBCFG_SW_MAJOR_VERSION              (1U)
#define PORT_PBCFG_SW_MINOR_VERSION              (0U)
#define PORT_PBCFG_SW_PATCH_VERSION              (0U)

/*
 * AUTOSAR Version 4.0.3
 */
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION     (4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION     (0U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION     (3U)

/* AUTOSAR Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION)\
  || (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION)\
  || (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
  #error "The AR version of Port_PBcfg.c does not match the expected version"
#endif

/* sOFTWARE vERSION CHECKING BETWEEN PORT_pbCFG AND PORT.H*/
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION)\
  || (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION)\
  || (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
  #error "The SW version of PBcfg.c does not match the expected version"
#endif


/* PB structure used with Port_Init API */
const port_ConfigType port_Configuration = {
        PORT_A, PA0, PORTA_PIN0_ID_INDEX, PORT_PIN_MODE_DIO, PORT_PIN_IN, NOT_OUTPUT, PULL_DOWN, STD_OFF, STD_OFF,
        NOT_USED, PA1, PORTA_PIN1_ID_INDEX, PORT_PIN_MODE_DIO, PORT_PIN_IN, NOT_OUTPUT, PULL_DOWN, STD_OFF, STD_OFF,
        PORT_A, PA2, PORTA_PIN2_ID_INDEX, PORT_PIN_MODE_DIO, PORT_PIN_IN, NOT_OUTPUT, PULL_DOWN, STD_OFF, STD_OFF,
        PORT_A, PA3, PORTA_PIN3_ID_INDEX, PORT_PIN_MODE_DIO, PORT_PIN_IN, NOT_OUTPUT, PULL_DOWN, STD_OFF, STD_OFF,
        PORT_A, PA4, PORTA_PIN4_ID_INDEX, PORT_PIN_MODE_DIO, PORT_PIN_IN, NOT_OUTPUT, PULL_DOWN, STD_OFF, STD_OFF,
        PORT_A, PA5, PORTA_PIN5_ID_INDEX, PORT_PIN_MODE_DIO, PORT_PIN_IN, NOT_OUTPUT, PULL_DOWN, STD_OFF, STD_OFF,
        PORT_A, PA6, PORTA_PIN6_ID_INDEX, PORT_PIN_MODE_DIO, PORT_PIN_IN, NOT_OUTPUT, PULL_DOWN, STD_OFF, STD_OFF,
        PORT_A, PA7, PORTA_PIN7_ID_INDEX, PORT_PIN_MODE_DIO, PORT_PIN_IN, NOT_OUTPUT, PULL_DOWN, STD_OFF, STD_OFF,
        PORT_B, PB0, PORTB_PIN0_ID_INDEX, PORT_PIN_MODE_DIO, PORT_PIN_OUT, PORT_PIN_LEVEL_HIGH, NOT_INPUT, STD_OFF, STD_OFF,
        PORT_B, PB1, PORTB_PIN1_ID_INDEX, PORT_PIN_MODE_DIO, PORT_PIN_OUT, PORT_PIN_LEVEL_HIGH, NOT_INPUT, STD_OFF, STD_OFF,
        PORT_B, PB2, PORTB_PIN2_ID_INDEX, PORT_PIN_MODE_DIO, PORT_PIN_OUT, PORT_PIN_LEVEL_HIGH, NOT_INPUT, STD_OFF, STD_OFF,
        PORT_B, PB3, PORTB_PIN3_ID_INDEX, PORT_PIN_MODE_DIO, PORT_PIN_OUT, PORT_PIN_LEVEL_HIGH, NOT_INPUT, STD_OFF, STD_OFF,
        PORT_B, PB4, PORTB_PIN4_ID_INDEX, PORT_PIN_MODE_DIO, PORT_PIN_OUT, PORT_PIN_LEVEL_HIGH, NOT_INPUT, STD_OFF, STD_OFF,
        PORT_B, PB5, PORTB_PIN5_ID_INDEX, PORT_PIN_MODE_DIO, PORT_PIN_OUT, PORT_PIN_LEVEL_HIGH, NOT_INPUT, STD_OFF, STD_OFF,
        PORT_B, PB6, PORTB_PIN6_ID_INDEX, PORT_PIN_MODE_DIO, PORT_PIN_OUT, PORT_PIN_LEVEL_HIGH, NOT_INPUT, STD_OFF, STD_OFF,
        PORT_B, PB7, PORTB_PIN7_ID_INDEX, PORT_PIN_MODE_DIO, PORT_PIN_OUT, PORT_PIN_LEVEL_HIGH, NOT_INPUT, STD_OFF, STD_OFF,
        NOT_USED, PC0, PORTC_PIN0_ID_INDEX, PORT_PIN_MODE_DIO, PORT_PIN_OUT, PORT_PIN_LEVEL_LOW, NOT_INPUT, STD_ON, STD_OFF,
        NOT_USED, PC1, PORTC_PIN1_ID_INDEX, PORT_PIN_MODE_DIO, PORT_PIN_OUT, PORT_PIN_LEVEL_LOW, NOT_INPUT, STD_ON, STD_OFF,
        NOT_USED, PC2, PORTC_PIN2_ID_INDEX, PORT_PIN_MODE_DIO, PORT_PIN_OUT, PORT_PIN_LEVEL_LOW, NOT_INPUT, STD_ON, STD_OFF,
        NOT_USED, PC3, PORTC_PIN3_ID_INDEX, PORT_PIN_MODE_DIO, PORT_PIN_OUT, PORT_PIN_LEVEL_LOW, NOT_INPUT, STD_ON, STD_OFF,
        NOT_USED, PC4, PORTC_PIN4_ID_INDEX, PORT_PIN_MODE_DIO, PORT_PIN_OUT, PORT_PIN_LEVEL_LOW, NOT_INPUT, STD_ON, STD_OFF,
        NOT_USED, PC5, PORTC_PIN5_ID_INDEX, PORT_PIN_MODE_DIO, PORT_PIN_OUT, PORT_PIN_LEVEL_LOW, NOT_INPUT, STD_ON, STD_OFF,
        NOT_USED, PC6, PORTC_PIN6_ID_INDEX, PORT_PIN_MODE_DIO, PORT_PIN_OUT, PORT_PIN_LEVEL_LOW, NOT_INPUT, STD_ON, STD_OFF,
        NOT_USED, PC7, PORTC_PIN7_ID_INDEX, PORT_PIN_MODE_DIO, PORT_PIN_OUT, PORT_PIN_LEVEL_LOW, NOT_INPUT, STD_ON, STD_OFF,
        PORT_D, PD0, PORTD_PIN0_ID_INDEX, PORT_PIN_MODE_DIO, PORT_PIN_OUT, PORT_PIN_LEVEL_HIGH, NOT_INPUT, STD_OFF, STD_OFF,
        PORT_D, PD1, PORTD_PIN1_ID_INDEX, PORT_PIN_MODE_DIO, PORT_PIN_OUT, PORT_PIN_LEVEL_HIGH, NOT_INPUT, STD_OFF, STD_OFF,
        PORT_D, PD2, PORTD_PIN2_ID_INDEX, PORT_PIN_MODE_DIO, PORT_PIN_OUT, PORT_PIN_LEVEL_HIGH, NOT_INPUT, STD_OFF, STD_OFF,
        PORT_D, PD3, PORTD_PIN3_ID_INDEX, PORT_PIN_MODE_DIO, PORT_PIN_OUT, PORT_PIN_LEVEL_HIGH, NOT_INPUT, STD_OFF, STD_OFF,
        PORT_D, PD4, PORTD_PIN4_ID_INDEX, PORT_PIN_MODE_DIO, PORT_PIN_OUT, PORT_PIN_LEVEL_HIGH, NOT_INPUT, STD_OFF, STD_OFF,
        PORT_D, PD5, PORTD_PIN5_ID_INDEX, PORT_PIN_MODE_DIO, PORT_PIN_OUT, PORT_PIN_LEVEL_HIGH, NOT_INPUT, STD_OFF, STD_OFF,
        PORT_D, PD6, PORTD_PIN6_ID_INDEX, PORT_PIN_MODE_DIO, PORT_PIN_OUT, PORT_PIN_LEVEL_HIGH, NOT_INPUT, STD_OFF, STD_OFF,
        PORT_D, PD7, PORTD_PIN7_ID_INDEX, PORT_PIN_MODE_DIO, PORT_PIN_OUT, PORT_PIN_LEVEL_HIGH, NOT_INPUT, STD_OFF, STD_OFF,
        PORT_E, PE0, PORTE_PIN0_ID_INDEX, PORT_PIN_MODE_DIO, PORT_PIN_OUT, PORT_PIN_LEVEL_HIGH, NOT_INPUT, STD_OFF, STD_OFF,
        PORT_E, PE1, PORTE_PIN1_ID_INDEX, PORT_PIN_MODE_DIO, PORT_PIN_OUT, PORT_PIN_LEVEL_HIGH, NOT_INPUT, STD_OFF, STD_OFF,
        PORT_E, PE2, PORTE_PIN2_ID_INDEX, PORT_PIN_MODE_DIO, PORT_PIN_OUT, PORT_PIN_LEVEL_HIGH, NOT_INPUT, STD_OFF, STD_OFF,
        PORT_E, PE3, PORTE_PIN3_ID_INDEX, PORT_PIN_MODE_DIO, PORT_PIN_OUT, PORT_PIN_LEVEL_HIGH, NOT_INPUT, STD_OFF, STD_OFF,
        PORT_E, PE4, PORTE_PIN4_ID_INDEX, PORT_PIN_MODE_DIO, PORT_PIN_OUT, PORT_PIN_LEVEL_HIGH, NOT_INPUT, STD_OFF, STD_OFF,
        PORT_E, PE5, PORTE_PIN5_ID_INDEX, PORT_PIN_MODE_DIO, PORT_PIN_OUT, PORT_PIN_LEVEL_HIGH, NOT_INPUT, STD_OFF, STD_OFF,
        PORT_F, PF0, PORTF_PIN0_ID_INDEX, PORT_PIN_MODE_DIO, PORT_PIN_IN, NOT_OUTPUT, PULL_UP, STD_OFF, STD_OFF,            //right but
        PORT_F, PF1, PORTF_PIN1_ID_INDEX, PORT_PIN_MODE_DIO, PORT_PIN_OUT, PORT_PIN_LEVEL_LOW, NOT_INPUT, STD_OFF, STD_OFF,
        NOT_USED, PF2, PORTF_PIN2_ID_INDEX, PORT_PIN_MODE_DIO, PORT_PIN_OUT, PORT_PIN_LEVEL_HIGH, NOT_INPUT, STD_OFF, STD_OFF,
        NOT_USED, PF3, PORTF_PIN3_ID_INDEX, PORT_PIN_MODE_DIO, PORT_PIN_OUT, PORT_PIN_LEVEL_HIGH, NOT_INPUT, STD_OFF, STD_OFF,
        NOT_USED, PF4, PORTF_PIN4_ID_INDEX, PORT_PIN_MODE_DIO, PORT_PIN_IN, NOT_OUTPUT, PULL_UP, STD_OFF, STD_OFF
};


